{
 "title": "Nokia SROS Network",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": { "query": "label_values(source)" } },
   {
    "name": "Network_Instance",
    "label": "Network_Instance",
    "query": {
     "query": "label_values(router_router_name)"
    }
   },
   {
    "name": "Interface",
    "label": "Interface",
    "query": {
     "query": "label_values(interface_interface_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Monitoring Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (source) (state_system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "count by (source) (state_system_cpu_summary_usage_cpu_usage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Packet Throughput",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(state_router_interface_ipv4_statistics_in_packets{}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(state_router_interface_ipv4_statistics_out_packets{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "state_system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top CPU Utilized Node",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(1, state_system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epipe R2-R3 Delay",
   "type": "gauge",
   "description": "DMM average from R02",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_oam_pm_session_ethernet_dmm_statistics_measurement_interval_number_bin_type_round_trip_average{bin_type_bin_metric=\"fd\", instance=\"clab-srmpls-gnmic:9804\", job=\"gnmic\", measurement_interval_duration=\"raw\", number_mi_number=\"1\", session_session_name=\"epipe_R2-R3\", source=\"clab-srmpls-r02-ixr:57400\", subscription_name=\"sub1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epipe R2-R3 Loss ratio",
   "type": "stat",
   "description": "backward SLM on R02",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "state_oam_pm_session_ethernet_slm_statistics_measurement_interval_number_backward_average_frame_loss_ratio{instance=\"clab-srmpls-gnmic:9804\", job=\"gnmic\", measurement_interval_duration=\"raw\", number_mi_number=\"1\", session_session_name=\"epipe_R2-R3\", source=\"clab-srmpls-r02-ixr:57400\", subscription_name=\"sub1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Current Memory In Use",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_system_memory_pools_summary_total_in_use{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STAMP R07-R09",
   "type": "timeseries",
   "description": "measured from R07",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "state_oam_pm_session_ip_twamp_light_statistics_delay_measurement_interval_number_bin_type_round_trip_average{source=\"clab-srmpls-r07-sr:57400\", session_session_name=\"toR09\", bin_type_bin_metric=\"fd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "State for $Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "Interface" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\",source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 21 },
   "targets": [
    {
     "expr": "state_system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\",source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Current Memory In Use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_system_memory_pools_summary_total_in_use{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Current Memory In Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "state_system_memory_pools_summary_total_in_use{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_port_oper_state{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(state_port_ethernet_statistics_in_unicast_packets{source=\"$Node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(state_port_ethernet_statistics_out_unicast_packets{source=\"$Node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(state_router_interface_statistics_ip_in_packets{source=\"$Node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(state_router_interface_statistics_ip_out_packets{source=\"$Node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}